#if (useDspGenerator)
//  This file is generated by a tool from the file ColorPaletteOverride.zip -- YOU SHOULD NOT EDIT IT manually.
#endif
using Uno.Extensions.Markup;

namespace PaliPractice.Styles;

public sealed partial class ColorPaletteOverride : ResourceDictionary
{
    public ColorPaletteOverride()
    {
        this.Build
        (r => r
            // PRIMARY — purple → ochre/orange
            .Add(Theme.Colors.Primary.Default,       light: "#B35C00", dark: "#FFC27A")
            .Add(Theme.Colors.Primary.Inverse,       light: "#FFD8B5", dark: "#6D2F00")
            .Add(Theme.Colors.Primary.Container,     light: "#FFE2C6", dark: "#6D3A00")
            .Add(Theme.Colors.OnPrimary.Default,     light: "#FFFFFF", dark: "#3A1E00")
            .Add(Theme.Colors.OnPrimary.Container,   light: "#3A1E00", dark: "#FFE7CF")

            // SECONDARY — lavender → muted ochre-brown
            .Add(Theme.Colors.Secondary.Default,     light: "#8A5A1A", dark: "#E2C39A")
            .Add(Theme.Colors.Secondary.Container,   light: "#F2D8B5", dark: "#5A3B14")
            .Add(Theme.Colors.OnSecondary.Default,   light: "#FFFFFF", dark: "#332D41") // kept neutral dark gray
            .Add(Theme.Colors.OnSecondary.Container, light: "#2F1600", dark: "#FFE2C6")

            // TERTIARY — unchanged
            .Add(Theme.Colors.Tertiary.Default,      light: "#0061A4", dark: "#9FCAFF")
            .Add(Theme.Colors.Tertiary.Container,    light: "#CFE4FF", dark: "#00497D")
            .Add(Theme.Colors.OnTertiary.Default,    light: "#FFFFFF", dark: "#003258")
            .Add(Theme.Colors.OnTertiary.Container,  light: "#001D36", dark: "#D1E4FF")

            // ERROR — unchanged
            .Add(Theme.Colors.Error.Default,         light: "#B3261E", dark: "#FFB4AB")
            .Add(Theme.Colors.Error.Container,       light: "#F9DEDC", dark: "#93000A")
            .Add(Theme.Colors.OnError.Default,       light: "#FFFFFF", dark: "#690005")
            .Add(Theme.Colors.OnError.Container,     light: "#410E0B", dark: "#FFDAD6")

            // BACKGROUNDS & SURFACES — neutrals preserved; only the purple tint changed
            .Add(Theme.Colors.Background.Default,    light: "#FCFBFF", dark: "#1C1B1F")
            .Add(Theme.Colors.OnBackground.Default,  light: "#1C1B1F", dark: "#E5E1E6")
            .Add(Theme.Colors.Surface.Default,       light: "#FFFFFF", dark: "#302D37")
            .Add(Theme.Colors.Surface.Variant,       light: "#F2EFF5", dark: "#47464F") // kept neutral-ish
            .Add(Theme.Colors.Surface.Inverse,       light: "#313033", dark: "#E6E1E5")
            .Add(Theme.Colors.Surface.Tint,          light: "#B35C00", dark: "#FFC27A") // was purple → ochre/orange
            .Add(Theme.Colors.OnSurface.Default,     light: "#1C1B1F", dark: "#E6E1E5")
            .Add(Theme.Colors.OnSurface.Variant,     light: "#8B8494", dark: "#C9C5D0")
            .Add(Theme.Colors.OnSurface.Inverse,     light: "#F4EFF4", dark: "#1C1B1F")

            // OUTLINES — unchanged (grays)
            .Add(Theme.Colors.Outline.Default,       light: "#79747E", dark: "#928F99")
            .Add(Theme.Colors.Outline.Variant,       light: "#C9C5D0", dark: "#57545D"));
    }
}
