global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using PaliPractice.Models;
global using PaliPractice.Presentation;
global using PaliPractice.Presentation.Common.Squircle;
global using PaliPractice.Presentation.Practice.ViewModels.Common;
global using PaliPractice.Services;
global using PaliPractice.Services.Database;
global using PaliPractice.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using Color = Windows.UI.Color;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
